// Single source of truth for the Spanish dialect the app targets.
// Everything generated by the app — AI feedback, session summaries, homework
// prompts, error notes, flashcards — must be ARGENTINE (rioplatense) Spanish
// with voseo. This module provides:
//
//   • A system-prompt fragment that can be injected into every LLM call
//   • A deterministic toVoseo() rewriter for static text, so hardcoded
//     Spanish templates and any programmatic prompts come out voseo-correct
//     even without an LLM in the loop.

export const LOCALE_NAME = 'Argentine Spanish (rioplatense, voseo)';

/**
 * System-prompt fragment to prepend/append to every OpenAI call that
 * produces Spanish text. Keep it short, declarative, and with concrete
 * examples; vague guidance ("sound natural") gets ignored by LLMs.
 */
export const ARGENTINE_SPANISH_STYLE_GUIDE = `LANGUAGE STYLE — ARGENTINE SPANISH (RIOPLATENSE, VOSEO). MANDATORY.

You are writing for a learner studying Spanish as it is spoken in Buenos Aires,
Argentina. ALL Spanish output you produce (feedback, corrections, vocabulary,
example sentences, tips, session summaries) MUST use rioplatense/porteño
Spanish with VOSEO. Follow these rules strictly:

1. Second-person singular pronoun is "vos", NEVER "tú".
2. Present-tense "vos" conjugations:
   - -ar verbs: vos hablás, pensás, tomás, practicás, usás
   - -er verbs: vos comés, tenés, querés, podés, entendés, ponés, sabés
   - -ir verbs: vos vivís, escribís, decís, venís, salís, seguís
   - Key irregulars: vos sos (not "eres"), vos vas, vos has (auxiliary)
3. Affirmative imperative for "vos" is formed by dropping the final "-r" of
   the infinitive and adding a written accent on the last syllable:
   - hablá, practicá, mirá, contá, tomá, usá, empezá, tratá
   - comé, leé, escribí, decí, vení, salí, elegí, repetí, seguí
   - Irregulars: decí (not "di"), hacé (not "haz"), poné (not "pon"),
     tené (not "ten"), vení (not "ven"), salí (not "sal"), sé (ser)
4. Negative imperative uses "no + subjunctive" with "vos" endings:
   - no hables, no comas, no digas, no vengas
5. Possessives and object pronouns stay the same as standard Spanish:
   "tu casa", "te lo digo", "para vos".
6. Preferred vocabulary where it differs:
   - ordenador → computadora;  coche → auto;  móvil/celu → celular;
     zumo → jugo;  gafas → anteojos / lentes;  pastel → torta;
     pluma → birome;  guay → copado / buenísimo;  vale → dale / ok;
     vosotros → ustedes (never use "vosotros" or its conjugations)
7. Forbidden forms — NEVER produce these in Spanish output:
   - "tú", "tú tienes", "tú eres", "contigo", "ti" as informal
   - tú-imperatives: "habla", "practica", "di", "haz", "pon", "ten",
     "ven", "sal", "escribe", "cuenta", "usa", "toma", "repite",
     "completa", "describe", "incluye", "elige", "piensa", "escucha"
     (use "hablá, practicá, decí, hacé, poné, tené, vení, salí, escribí,
     contá, usá, tomá, repetí, completá, describí, incluí, elegí, pensá,
     escuchá")
   - "vosotros" and all its conjugations
8. Tone: porteño — warm, encouraging, occasionally informal ("dale",
   "¡buenísimo!", "¿qué onda?"). Avoid peninsular ("vale", "tío").`;

/**
 * Deterministic tú→vos rewriter for static Spanish text. Intentionally
 * conservative — only targets common imperatives and second-person verb
 * forms that are safe to bulk-transform. Does NOT try to handle every case
 * (subordinate clauses, questions, reflexives) — those remain in source
 * files as voseo already, which is the easier path.
 *
 * Idempotent: running it on already-voseo text is a no-op.
 */
export function toVoseo(input: string): string {
  if (!input) return input;
  let out = input;

  // Simple word-level substitutions for the most common imperatives and
  // second-person forms found in app templates. Order matters — more
  // specific multi-word forms come first.
  const REPLACEMENTS: Array<[RegExp, string]> = [
    // Pronouns
    [/\btú\b/g, 'vos'],
    [/\bTú\b/g, 'Vos'],

    // Irregular imperatives (case-preserved by splitting the pattern).
    [/\bDi\b/g, 'Decí'],
    [/\bdi\b/g, 'decí'],
    [/\bHaz\b/g, 'Hacé'],
    [/\bhaz\b/g, 'hacé'],
    [/\bPon\b/g, 'Poné'],
    [/\bpon\b/g, 'poné'],
    [/\bTen\b/g, 'Tené'],
    [/\bten\b/g, 'tené'],
    [/\bVen\b/g, 'Vení'],
    [/\bven\b/g, 'vení'],
    [/\bSal\b/g, 'Salí'],
    [/\bsal\b/g, 'salí'],

    // Regular imperatives. Suffix-stripping rule: "-ar → -á", "-er → -é",
    // "-ir → -í". We encode a curated verb list rather than a generic rule
    // to avoid mangling false positives (e.g. "cosa", "toma" as a noun in
    // some contexts, etc.).
    ...([
      // -ar (imperative = stem + "á")
      ['Habla', 'Hablá'], ['habla', 'hablá'],
      ['Graba', 'Grabá'], ['graba', 'grabá'],
      ['Redacta', 'Redactá'], ['redacta', 'redactá'],
      ['Practica', 'Practicá'], ['practica', 'practicá'],
      ['Usa', 'Usá'], ['usa', 'usá'],
      ['Utiliza', 'Utilizá'], ['utiliza', 'utilizá'],
      ['Emplea', 'Empleá'], ['emplea', 'empleá'],
      ['Toma', 'Tomá'], ['toma', 'tomá'],
      ['Menciona', 'Mencioná'], ['menciona', 'mencioná'],
      ['Completa', 'Completá'], ['completa', 'completá'],
      ['Pregunta', 'Preguntá'], ['pregunta', 'preguntá'],
      ['Cuenta', 'Contá'], ['cuenta', 'contá'],
      ['Recuerda', 'Recordá'], ['recuerda', 'recordá'],
      ['Piensa', 'Pensá'], ['piensa', 'pensá'],
      ['Explica', 'Explicá'], ['explica', 'explicá'],
      ['Analiza', 'Analizá'], ['analiza', 'analizá'],
      ['Presenta', 'Presentá'], ['presenta', 'presentá'],
      ['Examina', 'Examiná'], ['examina', 'examiná'],
      ['Reflexiona', 'Reflexioná'], ['reflexiona', 'reflexioná'],
      ['Dibuja', 'Dibujá'], ['dibuja', 'dibujá'],
      ['Demuestra', 'Demostrá'], ['demuestra', 'demostrá'],
      ['Integra', 'Integrá'], ['integra', 'integrá'],
      ['Muestra', 'Mostrá'], ['muestra', 'mostrá'],
      ['Apunta', 'Apuntá'], ['apunta', 'apuntá'],
      ['Describe', 'Describí'], ['describe', 'describí'], // -ir
      ['Escribe', 'Escribí'], ['escribe', 'escribí'], // -ir
      ['Repite', 'Repetí'], ['repite', 'repetí'], // -ir
      ['Incluye', 'Incluí'], ['incluye', 'incluí'], // -ir
      ['Escoge', 'Elegí'], ['escoge', 'elegí'], // -er → use elegí
      ['Elige', 'Elegí'], ['elige', 'elegí'], // -ir
      ['Compone', 'Componé'], ['compone', 'componé'], // -er
      // Second-person indicatives (common in prompts): "haces" etc.
      ['tienes', 'tenés'], ['Tienes', 'Tenés'],
      ['eres', 'sos'], ['Eres', 'Sos'],
      ['haces', 'hacés'], ['Haces', 'Hacés'],
      ['dices', 'decís'], ['Dices', 'Decís'],
      ['puedes', 'podés'], ['Puedes', 'Podés'],
      ['quieres', 'querés'], ['Quieres', 'Querés'],
      ['sabes', 'sabés'], ['Sabes', 'Sabés'],
      ['conoces', 'conocés'], ['Conoces', 'Conocés'],
      ['vives', 'vivís'], ['Vives', 'Vivís'],
      ['vienes', 'venís'], ['Vienes', 'Venís'],
      ['sales', 'salís'], ['Sales', 'Salís'],
      ['sigues', 'seguís'], ['Sigues', 'Seguís'],
      ['pones', 'ponés'], ['Pones', 'Ponés'],
      ['entiendes', 'entendés'], ['Entiendes', 'Entendés'],
      ['piensas', 'pensás'], ['Piensas', 'Pensás'],
      ['hablas', 'hablás'], ['Hablas', 'Hablás'],
      ['tomas', 'tomás'], ['Tomas', 'Tomás'],
      ['usas', 'usás'], ['Usas', 'Usás'],
      ['aprendes', 'aprendés'], ['Aprendes', 'Aprendés'],
      // vosotros → ustedes (forbidden in rioplatense)
      ['vosotros', 'ustedes'], ['Vosotros', 'Ustedes'],
    ] as const).map(
      ([from, to]) => [new RegExp(`\\b${from}\\b`, 'g'), to] as [RegExp, string]
    ),
  ];

  for (const [pattern, replacement] of REPLACEMENTS) {
    out = out.replace(pattern, replacement);
  }
  return out;
}
